#!/bin/sh
## **************************************************************************
## For copyright and licensing terms, see the file named COPYING.
## **************************************************************************

name="system_control_normal"
daemon="/usr/local/bin/system-control"
daemon_flags="start --verbose normal"
rc_bg=YES

. /etc/rc.d/rc.subr

rc_pre()
{
	install -d -m 0755 /run/service-bundles/early-supervise
}

rc_cmd "$1"
