# vim: set filetype=sh:
# Common
service_with_dedicated_logger "ModemManager"
service_with_dedicated_logger "NetworkManager"
service_with_dedicated_logger "NetworkManager-dispatcher"
service_with_dedicated_logger "accounts-daemon"
service_with_dedicated_logger "bluetooth"
service_with_dedicated_logger "blueman-mechanism"
service_with_dedicated_logger "colord"
service_with_dedicated_logger "console-kit-daemon"
service_with_dedicated_logger "packagekit"
service_with_dedicated_logger "polkitd"
service_with_dedicated_logger "rtkit-daemon"
service_with_dedicated_logger "upower"
socket_with_dedicated_logger "avahi-daemon"
# Linux-specific
service_with_dedicated_logger "colord-sane"
service_with_dedicated_logger "udisks"
service_with_dedicated_logger "udisks2"
