# vim: set filetype=sh:
ktty_login_service_with_dedicated_logger "1"
ktty_login_service_with_dedicated_logger "2"
ktty_login_service_with_dedicated_logger "3"
ktty_login_service_with_dedicated_logger "4"
ktty_login_service_with_dedicated_logger "5"
ktty_login_service_with_dedicated_logger "6"
ktty_login_service_with_dedicated_logger "7"
ktty_login_service_with_dedicated_logger "8"
ktty_login_service_with_dedicated_logger "9"
ktty_login_service_with_dedicated_logger "10"
ktty_login_service_with_dedicated_logger "11"
ktty_login_service_with_dedicated_logger "12"
service_with_dedicated_logger "kernel-vt-loadkeys"
service_with_dedicated_logger "kernel-vt-setfont"
service_with_dedicated_logger "kernel-vt-setterm"
service_with_dedicated_logger "kernel-vt-kbdrate"
service_with_dedicated_logger "ttylogin-starter"
