#!/bin/sh -
case "$1" in
	remove|purge)
		for i in \
			console-fb-realizer@head0 \
			;
		do
			if system-control is-loaded $i.service
			then
				system-control unload-when-stopped $i.service
				system-control stop $i.service
			fi
			if system-control is-loaded cyclog@$i.service
			then
				system-control unload-when-stopped cyclog@$i.service
				system-control stop cyclog@$i.service
			fi
		done
		;;
esac
