#!/bin/sh -
case "$1" in
	upgrade)
		for i in \
			colord \
			colord-sane \
			console-kit-daemon \
			ModemManager \
			NetworkManager \
			packagekit \
			polkitd \
			udisks \
			upower \
			;
		do
			if system-control is-loaded $i.service
			then
				system-control try-restart $i.service
			fi
			if system-control is-loaded cyclog@$i.service
			then
				system-control try-restart cyclog@$i.service
			fi
		done
		;;
esac
