# vim: set filetype=sh:
# service list
# common targets, services, and sockets
service_with_dedicated_logger "motd-dynamic"
service_with_dedicated_logger "network-interfaces"
service_with_dedicated_logger "network-runtime"
service_with_dedicated_logger "nisdomain"
service_with_dedicated_logger "entropy"
service_with_dedicated_logger "ntpd"
service_with_dedicated_logger "ntpdate"
service_with_dedicated_logger "openntpd"
fan_in_logger "sysinit"
service_only "dmesg"
service_only_no_run "emergency-login@console"
service_only "hostname"
service_only "machine-id"
# BSD-specific targets, services, and sockets
service_with_dedicated_logger "sysctl"
service_with_dedicated_logger "savecore"
service_with_dedicated_logger "virecover"
service_with_dedicated_logger "vixiecron"
service_with_dedicated_logger "crashinfo"
service_with_dedicated_logger "cleanX"
service_with_dedicated_logger "cleantmp"
service_with_dedicated_logger "ipfw0"
service_with_dedicated_logger "ipfw"
service_with_dedicated_logger "iscsid"
service_with_dedicated_logger "newsyslog"
service_with_dedicated_logger "zfs"
service_with_dedicated_logger "zfsd"
service_with_dedicated_logger "kmod@fdescfs"
service_with_dedicated_logger "kmod@ipfw_nat"
service_with_dedicated_logger "kmod@libiconv"
service_with_dedicated_logger "kmod@libmchain"
service_with_dedicated_logger "kmod@linsysfs"
service_with_dedicated_logger "kmod@msdosfs_iconv"
service_with_dedicated_logger "kmod@sem"
fan_in_logger "devd"
service_only "devd"
service_only "kmod@fuse"
service_only "ldconfig"
service_only "nextboot"
service_only "gptboot"
# No WantedBy or StoppedBy, so do not need to preset
#target "graphics"
#target "halt"
#target "normal"
#target "powercycle"
#target "poweroff"
#target "reboot"
#target "shutdown"
#target "unmount"
# Has StoppedBy
target "extra-shared-libraries"
target "multi-user-pre"
target "name-services"
target "normal"
# has both
target "basic"
target "dumpauto"
target "frame-buffer"
target "fs-servers"
target "jails"
target "local-fs"
target "local-fs-pre"
target "local-syslog"
target "multi-user"
target "reboot-after-install"
target "reboot-after-update"
target "remote-fs"
target "remote-fs-pre"
target "server"
target "static-networking"
target "swapauto"
target "swaplate"
target "sysinit"
target "users"
target "workstation"
# has both, but should not be preset
#target "finish-install"
#target "finish-update"
