#!/bin/sh -e
if ! test -d package || ! test -d package/bsd
then
	echo "You are not in the right directory." 1>&2
	exit 100
fi

export CDPATH=

# Create and populate the bsd directory.
install -d -m 0755 bsd
( cd package/bsd && ( 2>/dev/null pax -w -r -l -u -- * ../../bsd/ || true ) )
