#!/bin/sh -e
redo-ifchange ./cxx ./cxxflags ./cppflags
read cxx < ./cxx
read cxxflags < ./cxxflags
read cppflags < ./cppflags
${cxx} ${cxxflags} ${cppflags} -o "$1" -c "$2" -MMD -MF "$3" 
sed -e "s!^$1: *!!" -e 's/\\$//g' "$3" | xargs -r redo-ifchange
