#!/bin/sh
echo "digraph services {"
for i in /etc/service-bundles/targets/*
do
	test -e "$i/service/down" && continue
	echo "\"$i\"" "[shape=octagon,style=\"rounded,filled\",fillcolor=yellow]" ";"
done
for i in /var/sv/* /var/local/sv/* /etc/service-bundles/services/* /etc/service-bundles/targets/*
do
	test -e "$i/service/down" && continue
	find "$i/after/" -type l 2>/dev/null |
	while read -r j
	do
		test "`basename \"$j\"`" = sockets && continue
		k="`readlink -f \"$j\"`"
		test -z "$k" && continue
		echo "\"$k\"" "->" "\"$i\"" ";"
	done
	find "$i/before/" -type l 2>/dev/null |
	while read -r j
	do
		test "`basename \"$j\"`" = sockets && continue
		k="`readlink -f \"$j\"`"
		test -z "$k" && continue
		echo "\"$i\"" "->" "\"$k\"" ";"
	done
done
echo "}"
