#!/bin/sh -e
## **************************************************************************
## For copyright and licensing terms, see the file named COPYING.
## **************************************************************************
# vim: set filetype=sh:
objects='object/BaseTUI.o object/CompositeFont.o object/DefaultEnvironment.o object/ECMA48Decoder.o object/ECMA48Output.o object/FileDescriptorOwner.o object/FontLoader.o object/GraphicsInterface.o object/InputFIFO.o object/IPAddress.o object/LoginBannerInformation.o object/LoginClassRecordOwner.o object/MapColours.o object/ProcessEnvironment.o object/SignalManagement.o object/SoftTerm.o object/TerminalCapabilities.o object/TUIDisplayCompositor.o object/TUIInputBase.o object/TUIOutputBase.o object/TUIVIO.o object/TUIVIOWidgets.o object/UTF16Decoder.o object/UTF8Decoder.o object/UTF8Encoder.o object/UnicodeClassification.o object/UnicodeKeyboard.o object/UserEnvironmentSetter.o object/VirtualTerminalBackEnd.o object/VirtualTerminalRealizer.o object/VisDecoder.o object/VisEncoder.o object/basename.o object/begins_with.o object/bundle_creation.o object/comment.o object/control_groups.o object/convert_args.o object/dirname.o object/ends_in.o object/error_and_usage_messages.o object/fstab_options.o object/getaddrinfo_unix.o object/home_dir.o object/host_id.o object/iovec.o object/is_bool.o object/is_jail.o object/is_set_hostname_allowed.o object/kbdmap_bsd_keycode_to_index.o object/kbdmap_default.o object/kbdmap_evdev_keycode_to_index.o object/kbdmap_usb_ident_to_index.o object/listen.o object/log_dir.o object/machine_id.o object/nmount.o object/open_exec.o object/open_lockfile.o object/open_lockfile_or_wait.o object/pack.o object/pipe_close_on_exec.o object/popt-bool.o object/popt-bool-string.o object/popt-compound-1arg.o object/popt-compound-2arg.o object/popt-integral.o object/popt-named.o object/popt.o object/popt-signed.o object/popt-simple.o object/popt-size.o object/popt-string-list.o object/popt-string-pair-list.o object/popt-string-pair.o object/popt-string.o object/popt-table.o object/popt-top-table.o object/popt-tui-level.o object/popt-unsigned.o object/process_env_dir.o object/quote.o object/raw.o object/read_env_file.o object/read_line.o object/read-file.o object/runtime_dir.o object/sane.o object/setprocargv.o object/setprocenvv.o object/setprocname.o object/socket_close_on_exec.o object/socket_connect.o object/socket_set_option.o object/signame.o object/split_list.o object/subreaper.o object/systemd_names.o object/tai64.o object/terminal_database.o object/tcgetattr.o object/tcgetwinsz.o object/tcsetattr.o object/tcsetwinsz.o object/tolower.o object/trim.o object/ttyname.o object/u32string.o object/unpack.o object/val.o object/wait.o'
case "`uname`" in
(Linux)	platform_objects='object/kqueue_linux.o';;
(*)	platform_objects='';;
esac
redo-ifchange ./archive ${objects} ${platform_objects}
./archive "$3" ${objects} ${platform_objects}
