#!/bin/sh -e
# See http://skarnet.org./software/compile.html
if [ \! -d package -o \! -d source ]
then
	echo "You are not in the right directory." 1>&2
	exit 100
fi

# Rebuild.
case "`uname`" in
Linux) cpus="`fgrep -c processor /proc/cpuinfo`" ;;
*BSD) cpus=4 ;;
esac
redo --directory build --jobs "${cpus}" -- all
