#!/bin/sh -e
if [ \! -d package ] || [ \! -d source ]
then
	echo "You are not in the right directory." 1>&2
	exit 100
fi
cwd="`/bin/pwd`"
base_plus_version="`basename "${cwd}"`"
tar --create --bzip2 --file "${base_plus_version}.tar.bz2" source package
